### ISSUE TITLE
Investigate slowness

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#3366]
# My findings:

```
Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: /usr/share/wildfly10/standalone/tmp/vfs/temp/temp60c58a60bdeb9fe7/content-524eff66e0980ca7/resources/theme-muikku: Too many open files
        at io.undertow.server.handlers.resource.PathResource.list(PathResource.java:88)
        at org.wildfly.extension.undertow.deployment.ServletResourceManager.list(ServletResourceManager.java:106)
        at org.wildfly.extension.undertow.deployment.ServletResource.list(ServletResource.java:85)
        at io.undertow.server.handlers.resource.CachedResource.list(CachedResource.java:107)
        at io.undertow.servlet.spec.ServletContextImpl.getResourcePaths(ServletContextImpl.java:220)
        at com.sun.faces.context.ExternalContextImpl.getResourcePaths(ExternalContextImpl.java:533)
        at com.sun.faces.application.resource.WebappResourceHelper.findLibrary(WebappResourceHelper.java:196)
        at com.sun.faces.application.resource.ResourceManager.findLibrary(ResourceManager.java:467)
        at com.sun.faces.application.resource.ResourceManager.getResourceInfo(ResourceManager.java:291)
        at com.sun.faces.application.resource.ResourceManager.doLookup(ResourceManager.java:285)
        at com.sun.faces.application.resource.ResourceManager.findResource(ResourceManager.java:214)
        at com.sun.faces.application.resource.ResourceManager.findResource(ResourceManager.java:179)
        at com.sun.faces.application.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:201)
        at com.sun.faces.application.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:181)
        at com.sun.faces.application.resource.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:325)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:655)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at fi.otavanopisto.muikku.LocalSessionFilter.doFilter(LocalSessionFilter.java:42)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:265)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:200)
        at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:193)
        ... 42 more
Caused by: java.nio.file.FileSystemException: /usr/share/wildfly10/standalone/tmp/vfs/temp/temp60c58a60bdeb9fe7/content-524eff66e0980ca7/resources/theme-muikku: Too many open files
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
        at io.undertow.server.handlers.resource.PathResource.list(PathResource.java:83)
        ... 74 more
```
Apparently Muikku is leaking file handles. This manifested now only because it hasn't been rebooted in several weeks.

**Comment by ilmoeuro** [comment]
The reason is because Undertow has *no timeout* by default, and WebSocket connections are left lingering. Should we set a timeout, and let some websocket connections fail and reconnect if there's no traffic?

Here's how to configure the timeout:

https://wildscribe.github.io/Wildfly/8.2.0.Final/subsystem/undertow/server/http-listener/index.html

**Comment by pkukkon** [comment]
Most likely related to the server running out of resources. After lengthy periods of time, memory pool is exhausted and the application crawls to a halt, not being able to perform garbage collecting.

Latest issue to address the core problem would most likely be #3774.

**Comment by anttiviljakainen** [comment]
Memory situation is now much better - however file handles are likely leaked.
